"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By considering the terms in the Fibonacci sequence whose values do not exceed N, find the sum of the even-valued terms.
"""

t = int(input())

for _ in range(t):
    n = int(input())
    sum = 0
    
    first = 1
    second = 2
    
    while second <= n:
        if second % 2 == 0:
            sum += second
        
        temp = second
        second = first + second
        first = temp
    
    print(sum)
